"""empty message

Revision ID: b91974ca72a7
Revises: 
Create Date: 2018-07-20 03:53:19.058813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b91974ca72a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freelancer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=50), nullable=True),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.Column('skills', sa.String(length=500), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('job_postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.String(length=200), nullable=True),
    sa.Column('no_of_people', sa.Integer(), nullable=True),
    sa.Column('posted_by', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_postings')
    op.drop_table('freelancer')
    # ### end Alembic commands ###
